### ISSUE TITLE
auditsea - The formula for calculating price change is incorrect in Exp price adapter.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-Index-judging#5]
auditsea

medium

# The formula for calculating price change is incorrect in Exp price adapter.

## Summary
In `BoundedStepwiseExponentialPriceAdapter`, there's a formula to calculate the price change and it is incorrect for normalization.

## Vulnerability Detail
https://github.com/sherlock-audit/2023-06-Index/blob/main/index-protocol/contracts/protocol/integration/auction-price/BoundedStepwiseExponentialPriceAdapter.sol#L73C67-L73C67

The formula is `scalingFactor * expExpression - WAD`, but the correct normalization has to be `scalingFactor * (expExpression - WAD)`

## Impact
This issue leads to unexpected and/or unwanted price graph.

## Tool used

Manual Review

## Recommendation
Update the formula as described above. 🫡

Duplicate of #39

**Comment by 0xmonrel** [comment]
Escalate 

This should be a duplicate of #39 and not #1

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> This should be a duplicate of #39 and not #1 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #39

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xmonrel](https://github.com/sherlock-audit/2023-06-Index-judging/issues/5/#issuecomment-1658155616): accepted
