### ISSUE TITLE
Cryptor - Lack of an expiry can result in loss of user funds through MEV

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-Index-judging#7]
Cryptor

high

# Lack of an expiry can result in loss of user funds through MEV

## Summary
A lack of an expiry could result in a loss of user funds through MEV

## Vulnerability Detail

https://github.com/sherlock-audit/2023-06-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L309-L314

The function bid lacks a parameter to let bids expire after a certain time has passed. This is dangerous. On many chains, transactions can be held by validators, prompting a MEV sandwich attack, where a malicious validator can front run a bidder by calling issue in the settoken contract, hold the bidder's transaction, and then calling redeem after the bidder calls the function bid.  Depending on the adapter settings, users would be left vulnerable to significant price swings, resulting in an unexpected loss of funds where quoteassetlimit parameter will not be sufficient as slippage protection. 

## Impact
Users could lose funds due to a lack of an expiry in the bid function

## Code Snippet
https://github.com/sherlock-audit/2023-06-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L309-L314

## Tool used

Manual Review

## Recommendation
Add an expiration date so that users do not lose funds from malicious validators

**Comment by JJtheAndroid** [comment]
Escalate 

I think this issue is valid 

A lack of an expiry can be devastating for users. Without it, users are still vulnerable to slippage and quoteassetlimit is not sufficient as slippage protection

**Comment by pblivin0x** [comment]
I believe these checks are sufficient to protect the bidder against
- any time delays in their bid
- any issuance or redemption before their bid

When the bidder formulates their bid, they can set 
`quoteQuantityLimit = componentQuantity * expectedPrice * totalSupply`

https://github.com/sherlock-audit/2023-06-Index/blob/8d348ed344635a068d458aa04956f966b6d3d4f3/index-protocol/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L869-L871

**Comment by pblivin0x** [comment]
> Escalate
> 
> I think this issue is valid
> 
> A lack of an expiry can be devastating for users. Without it, users are still vulnerable to slippage and quoteassetlimit is not sufficient as slippage protection

My final opinion is this is invalid, the bidder has the ability to protect themselves with `quoteQuantityLimit`, and dutch auctions price will move in favor of the bidder over time

**Comment by JJtheAndroid** [comment]
I disagree here. For one dutch auctions only moves in favor of the bidder if set token manager makes it decreasing. Also quoteQuantityLimit doesn't really work because a user cannot reasonably predict how long their transaction stays in the mempool.

**Comment by pblivin0x** [comment]
> I disagree here. For one dutch auctions only moves in favor of the bidder if set token manager makes it decreasing. Also quoteQuantityLimit doesn't really work because a user cannot reasonably predict how long their transaction stays in the mempool.

The user does not have to predict how long their transaction stays in the mempool. 

By selecting a `quoteQuantityLimit`, they are implicitly setting an expiration, because the auction price curve is fixed, and will intersect with `quoteQuantityLimit` and a known time

**Comment by pblivin0x** [comment]
> So any asset price below quoteQuantityLimit is susceptible to MEV if the auction is increasing. One can argue that the user entered the wrong quoteQuantityLimit in this scenario, but I cannot see how this could be invalid while this issue is a [med](https://github.com/sherlock-audit/2023-06-Index-judging/issues/40#issuecomment-1664134005)
> 
> Both issues steam from bad inputs from trusted parties I will leave this to the judges. Thanks for the fruitful discussions.

In a sell auction, the `bidder` is providing some amount of `quoteAsset` in exchange for `component`. 
+ Price,  the ratio of `quoteAsset` per `component`, will decrease over time
    + Meaning that the exchange gets more attractive for the bidder over time, because they will have to pay less `quoteAsset` to get the same amount of `component`
+ The `quoteQuantityLimit` is enforced as a maximum expenditure of `quoteAsset` https://github.com/IndexCoop/index-protocol/blob/3700ae5a34facc9b24d353188f8fbd6ea738fd32/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L869

After the bidder submits their `bid` on a sell auction, if there is any time delay, the amount of `quoteAsset` their bid spends is strictly non-increasing. 

In a buy auction, the `bidder` is providing some amount of `component` in exchange for `quoteAsset`. 
+ Price,  the ratio of `quoteAsset` per `component`, will increase over time
    + Meaning that the deal exchange gets more attractive for the bidder over time, because they will get more `quoteAsset` by providing the same amount of `component`
+ The `quoteQuantityLimit` is enforced as a minimum output of `quoteAsset` https://github.com/IndexCoop/index-protocol/blob/3700ae5a34facc9b24d353188f8fbd6ea738fd32/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L871

After the bidder submits there `bid`, if there is any time delay, the amount of `quoteAsset` their bid outputs is strictly non-decreasing.

**Comment by lepLinus** [comment]
> 

This explains it well. I belief this is invalid. In any bid that is executed further away from auction start will benefit the bidder.

**Comment by Oot2k** [comment]
> > So any asset price below quoteQuantityLimit is susceptible to MEV if the auction is increasing. One can argue that the user entered the wrong quoteQuantityLimit in this scenario, but I cannot see how this could be invalid while this issue is a [med](https://github.com/sherlock-audit/2023-06-Index-judging/issues/40#issuecomment-1664134005)
> > Both issues steam from bad inputs from trusted parties I will leave this to the judges. Thanks for the fruitful discussions.
> 
> In a sell auction, the `bidder` is providing some amount of `quoteAsset` in exchange for `component`.
> 
> * Price,  the ratio of `quoteAsset` per `component`, will decrease over time
>   
>   * Meaning that the exchange gets more attractive for the bidder over time, because they will have to pay less `quoteAsset` to get the same amount of `component`
> * The `quoteQuantityLimit` is enforced as a maximum expenditure of `quoteAsset` https://github.com/IndexCoop/index-protocol/blob/3700ae5a34facc9b24d353188f8fbd6ea738fd32/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L869
> 
> After the bidder submits their `bid` on a sell auction, if there is any time delay, the amount of `quoteAsset` their bid spends is strictly non-increasing.
> 
> In a buy auction, the `bidder` is providing some amount of `component` in exchange for `quoteAsset`.
> 
> * Price,  the ratio of `quoteAsset` per `component`, will increase over time
>   
>   * Meaning that the deal exchange gets more attractive for the bidder over time, because they will get more `quoteAsset` by providing the same amount of `component`
> * The `quoteQuantityLimit` is enforced as a minimum output of `quoteAsset` https://github.com/IndexCoop/index-protocol/blob/3700ae5a34facc9b24d353188f8fbd6ea738fd32/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L871
> 
> After the bidder submits there `bid`, if there is any time delay, the amount of `quoteAsset` their bid outputs is strictly non-decreasing.

This explains it well. I belief this is invalid. In any bid that is executed further away from auction start will benefit the bidder.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above comment:
https://github.com/sherlock-audit/2023-06-Index-judging/issues/7#issuecomment-1664735283

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [JJtheAndroid](https://github.com/sherlock-audit/2023-06-Index-judging/issues/7/#issuecomment-1658356688): rejected
