### ISSUE TITLE
auditsea - Early unlock will not work forever once `raiseTargetPercentage` is set by a manager in auction rebalance module

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-Index-judging#9]
auditsea

medium

# Early unlock will not work forever once `raiseTargetPercentage` is set by a manager in auction rebalance module

## Summary
Early unlock will not work forever once `raiseTargetPercentage` is set by a manager.

## Vulnerability Detail
In `unlock` function, it provides a feature to early unlock the `setToken` when all conditions are met before the auction ends.
One of conditions is that `raiseTargetPercentage` must be zero.
The `raiseTargetPercentage` is set by a manager in `setRaiseTargetPercentage` function, but it requires the `raiseTargetPercentage` to be greater than zero, which means it can not be set back to zero.
As long as `raiseTargetPercentage` remains positive, early unlock functionality will not work.

## Impact
Early unlock feature won't be working forever.

## Code Snippet
https://github.com/sherlock-audit/2023-06-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L1201

https://github.com/sherlock-audit/2023-06-Index/blob/main/index-protocol/contracts/protocol/modules/v1/AuctionRebalanceModuleV1.sol#L421

## Tool used

Manual Review

## Recommendation
Accept zero value for `raiseTargetPercentage`

Duplicate of #38

**Comment by 0xmonrel** [comment]
Escalate 

This is a duplicate of #38

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> This is a duplicate of #38 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Oot2k** [comment]
Agree with escalation

**Comment by pblivin0x** [comment]
Agree, as part of the audit remediations we remove the condition that  `setRaiseTargetPercentage` does not accept input 0

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #38

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xmonrel](https://github.com/sherlock-audit/2023-06-Index-judging/issues/9/#issuecomment-1658140681): accepted
